let projects = [
    {id: 1, 
        name: 'تاریخ تولد', 
        discription: 'یک لیست از افرادی که تولدشان هست را میبنیم و میتوانیم این لیست را پاک کنیم .',
        level: 'ساده', 
        image: '/React-Mini-Projects/images/project-1.png',
        url: '/1-birthday', 
        github: 'https://github.com/rezanahi/React-Mini-Projects/blob/main/src/pages/1-birthday/Birthday.js'},
    {id: 2, 
        name: 'لیست تور ها', 
        discription: 'یک لیست از تورهای حاضر است میتوانید اطلاعات هر تور را ببینید و همچنین اطلاعات بیشتری را نیز مشاهده کنید و درصورتی که علاقه ای به تور نداشتید آنرا حذف کنید درصورت حذف تمام تورها امکان رفرش اطلاعات وجود دارد',
        level: 'ساده', 
        image: '/React-Mini-Projects/images/project-2.png',
        url: '/2-tours', 
        github: 'https://github.com/rezanahi/React-Mini-Projects/blob/main/src/pages/2-tours/Tours.jsx'},
    {id: 3, 
        name: 'نظرات', 
        discription: 'میتوانید نظرات مخاطبین را ببینید و به نظرات قبلی و بعدی بروید ، همچنین میتوانید به صورت رندوم نظرات را مشاهده کنید',
        level: 'ساده', 
        image: '/React-Mini-Projects/images/project-3.png',
        url: '/3-reviews', 
        github: 'https://github.com/rezanahi/React-Mini-Projects/blob/main/src/pages/3-reviews/Reviews.jsx'},
    {id: 4, 
        name: 'آکاردئون', 
        discription: 'روی آیکون هر عنوان کلیک کنید تا بتوانید توضیحات بیشتری را مشاهده نمایید ',
        level: 'ساده', 
        image: '/React-Mini-Projects/images/project-4.png',
        url: '/4-accordion', 
        github: 'https://github.com/rezanahi/React-Mini-Projects/blob/main/src/pages/4-accordion/Accordion.jsx'},
    {id: 5, 
        name: 'منوی غذا', 
        discription: 'منو را مشاهده کرده و غذای مورد علاقه خودرا انتخاب کنید ، همچنین میتوانید براساس دسته بندی های مختلف نتایج را فیلتر کنید',
        level: 'متوسط', 
        image: '/React-Mini-Projects/images/project-5.png',
        url: '/5-foodmenu', 
        github: 'https://github.com/rezanahi/React-Mini-Projects/blob/main/src/pages/5-menu/FoodMenu.jsx'},
    {id: 6, 
        name: 'تَب ها', 
        discription: 'اطلاعات مربوط به هر تجربه کاری را با کلیک روی هر تَب میتوانید مشاهده کنید و همچنین از تجربه ریسپانسیو بودن صفحه لذت ببرید',
        level: 'ساده', 
        image: '/React-Mini-Projects/images/project-6.png',
        url: '/6-tabs', 
        github: 'https://github.com/rezanahi/React-Mini-Projects/blob/main/src/pages/6-tabs/Tabs.jsx'},
    {id: 7, 
        name: 'اسلایدر', 
        discription: 'نظرت مخاطبان را در یک اسلایدر زیبا با انیمیشن های جذاب میتوانید مشاهده کنید ، همچنین به صورت خودکار نیز نظرات جابجا میشوند',
        level: 'متوسط', 
        image: '/React-Mini-Projects/images/project-7.png',
        url: '/7-slider', 
        github: 'https://github.com/rezanahi/React-Mini-Projects/blob/main/src/pages/7-slider/Slider.jsx'},
    {id: 8, 
        name: 'تولید کننده لورم', 
        discription: 'تعداد پاراگراف های دلخواه خود را وارد کنید و روی دکمه تولید کلیک کرده تا به همان تعداد متن تصادفی دریافت کنید ، حداکثر تا 9 پاراگراف متن تصادفی خواهید داشت',
        level: 'ساده', 
        image: '/React-Mini-Projects/images/project-8.png',
        url: '/8-lorem', 
        github: 'https://github.com/rezanahi/React-Mini-Projects/blob/main/src/pages/8-lorem/Lorem.jsx'},
    {id: 9, 
        name: 'تولید کننده سایه', 
        discription: 'کد هگز رنگ مدنظر را وارد کنید و ثبت کنید تا تعداد ده سایه روشن و ده سایه تیره از همان رنگ دریافت کنید ، همچنین با کلیک روی هر رنگ کد هگز آن کپی میشود',
        level: 'متوسط', 
        image: '/React-Mini-Projects/images/project-9.png',
        url: '/9-color', 
        github: 'https://github.com/rezanahi/React-Mini-Projects/blob/main/src/pages/9-color/Color.jsx'},
    {id: 10, 
        name: 'تودو لیست', 
        discription: 'اسم تسک خودرا وارد کرده و آنرا ثبت کنید تا به لیست اضافه شود شما میتوانید هر تسک را پس از تکمیل حذف کنید یا ویرایش کنید و همچنین میتوانید همزمان تسک هارا پاک کنید',
        level: 'پیشرفته', 
        image: '/React-Mini-Projects/images/project-10-todolist.png',
        url: '/10-todolist', 
        github: 'https://github.com/rezanahi/React-Mini-Projects/blob/main/src/pages/10-todolist/ToDoList.jsx'},
    {id: 11, 
        name: 'منو ریسپانسیو', 
        discription: 'یک منو ریسپانسیو با انیمیشن زیبا در حالت موبایل :)',
        level: 'ساده', 
        image: '/React-Mini-Projects/images/project-11.png',
        url: '/11-navbar', 
        github: 'https://github.com/rezanahi/React-Mini-Projects/blob/main/src/pages/11-navbar-project/NavBarProject.jsx'},
    {id: 12, 
        name: 'سایدبار', 
        discription: 'مدال و سایدبار را باز و بسته کنید و از قدرت کانتکست ای پی آی در ری اکت لذت ببرید',
        level: 'ساده', 
        image: '/React-Mini-Projects/images/project-12.png',
        url: '/12-sidebar', 
        github: 'https://github.com/rezanahi/React-Mini-Projects/blob/main/src/pages/12-sidebar-project/SideBarProject.jsx'},
    {id: 13, 
        name: 'استرایپ', 
        discription: 'روی لینک های منو هاور کنید تا زیرمنو ها در موقعیت مناسب برای شما باز شود . همچنین در حالت موبایل هم یک مدال در مرکز صفحه خواهید داشت',
        level: 'پیشرفته', 
        image: '/React-Mini-Projects/images/project-13.png',
        url: '/13-stripe', 
        github: 'https://github.com/rezanahi/React-Mini-Projects/blob/main/src/pages/13-stripe/Stripe.jsx'},
    {id: 14, 
        name: 'سبدخرید', 
        discription: 'تعداد محصولات سبدخرید خود را کم یا زیاد کنید و قیمت نهایی و همچنین تعداد محصولات داخل سبدخرید خود را مشاهده کنید . همچنین میتوانید آنهارا کاملا حذف کنید',
        level: 'پیشرفته', 
        image: '/React-Mini-Projects/images/project-14.png',
        url: '/14-cart', 
        github: 'https://github.com/rezanahi/React-Mini-Projects/blob/main/src/pages/14-cart-project/CartProject.jsx'},
    {id: 15, 
        name: 'کوکتل ها', 
        discription: 'یک منوی کامل را مشاهده میکنید و همچنین میتوانید به جستجوی دلخواه بپردازید ، با کمک ای پی آی کوکتل یک لیست کامل را مشاهده خواهید کرد',
        level: 'پیشرفته', 
        image: '/React-Mini-Projects/images/project-15.png',
        url: '/15-cocktails', 
        github: 'https://github.com/rezanahi/React-Mini-Projects/blob/main/src/pages/15-cocktails/Cocktails.jsx'},
]


export default projects